// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qerymtenumzekndpfmnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlcnltdGVudW16ZWtuZHBmbW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyMjM0MzgsImV4cCI6MjA3OTc5OTQzOH0.xuML-GQOG61xPKHSeTJThThKG5UsFKWM9NQsFwumOmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});